version: '3.10'
services:
  docker-fastapi-app:
    container_name: docker-fastapi-app
    build:
      context: ./app/
      dockerfile: Dockerfile
    restart: always
  nginx:
    depends_on:
      - docker-fastapi-app
    container_name: proxy-app
    build:
      context: ./client-studia/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: always
