"""add timestamp to auth model

Revision ID: 179b0b57c484
Revises: a854b6be4a62
Create Date: 2023-04-15 10:23:08.459825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179b0b57c484'
down_revision = 'a854b6be4a62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('craeted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('email_verification', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile', sa.Column('craeted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'updated_at')
    op.drop_column('profile', 'craeted_at')
    op.drop_column('email_verification', 'updated_at')
    op.drop_column('email_verification', 'craeted_at')
    # ### end Alembic commands ###
