"""add_name_and_color_hex_to_class

Revision ID: bb9a172bff59
Revises: a2781a18c7c9
Create Date: 2023-05-06 12:29:13.371773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9a172bff59'
down_revision = 'a2781a18c7c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('class', sa.Column('color_hex', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'color_hex')
    op.drop_column('class', 'name')
    # ### end Alembic commands ###
