"""add_on_delete_cascade

Revision ID: d3ce0bbcee3b
Revises: bb9a172bff59
Create Date: 2023-05-12 19:00:24.724909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ce0bbcee3b'
down_revision = 'bb9a172bff59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('class_owner_id_fkey', 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_class_class_id_fkey', 'user_class', type_='foreignkey')
    op.create_foreign_key(None, 'user_class', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_class', type_='foreignkey')
    op.create_foreign_key('user_class_class_id_fkey', 'user_class', 'class', ['class_id'], ['id'])
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key('class_owner_id_fkey', 'class', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
